version: '3.8'
services:
  dapp:
    build:
      context: .
      args:
        REACT_APP_DEFAULT_BRIDGE_DIRECTION: ${REACT_APP_DEFAULT_BRIDGE_DIRECTION}
        REACT_APP_ENABLED_BRIDGES: ${REACT_APP_ENABLED_BRIDGES}
        REACT_APP_INFURA_ID: ${REACT_APP_INFURA_ID}
        REACT_APP_GAS_PRICE_FALLBACK_GWEI: ${REACT_APP_GAS_PRICE_FALLBACK_GWEI}
        REACT_APP_GAS_PRICE_SUPPLIER_URL: ${REACT_APP_GAS_PRICE_SUPPLIER_URL}
        REACT_APP_GAS_PRICE_SPEED_TYPE: ${REACT_APP_GAS_PRICE_SPEED_TYPE}
        REACT_APP_GAS_PRICE_UPDATE_INTERVAL: ${REACT_APP_GAS_PRICE_UPDATE_INTERVAL}
        REACT_APP_ETH_PRICE_API_URL: ${REACT_APP_ETH_PRICE_API_URL}
        REACT_APP_ETH_PRICE_UPDATE_INTERVAL: ${REACT_APP_ETH_PRICE_UPDATE_INTERVAL}
        REACT_APP_TITLE: ${REACT_APP_TITLE}
        REACT_APP_DESCRIPTION: ${REACT_APP_DESCRIPTION}
        REACT_APP_UI_STATUS_UPDATE_INTERVAL: ${REACT_APP_UI_STATUS_UPDATE_INTERVAL}
        REACT_APP_DEBUG_LOGS: ${REACT_APP_DEBUG_LOGS}
        REACT_APP_GRAPH_HEALTH_UPDATE_INTERVAL: ${REACT_APP_GRAPH_HEALTH_UPDATE_INTERVAL}
        REACT_APP_GRAPH_HEALTH_THRESHOLD_BLOCKS: ${REACT_APP_GRAPH_HEALTH_THRESHOLD_BLOCKS}
        REACT_APP_XDAI_RPC_URL: ${REACT_APP_XDAI_RPC_URL}
        REACT_APP_POA_RPC_URL: ${REACT_APP_POA_RPC_URL}
        REACT_APP_SOKOL_RPC_URL: ${REACT_APP_SOKOL_RPC_URL}
        REACT_APP_MAINNET_RPC_URL: ${REACT_APP_MAINNET_RPC_URL}
        REACT_APP_KOVAN_RPC_URL: ${REACT_APP_KOVAN_RPC_URL}
        REACT_APP_BSC_RPC_URL: ${REACT_APP_BSC_RPC_URL}
        REACT_APP_COINZILLA_API_KEY: ${REACT_APP_COINZILLA_API_KEY}
        REACT_APP_OWLRACLE_API_KEY: ${REACT_APP_OWLRACLE_API_KEY}
        REACT_APP_SENTRY_DSN: ${REACT_APP_SENTRY_DSN}
    ports:
      - 3000:3000
